### PR TITLE
Added browser platform; Use the latest AccountKit SDK for both iOS and Android platform

### PR DESCRIPTION
**Pull request by eddy-lau**

### CODE REVIEW

**Comment by gurisko** [comment]
Hey @eddy-lau ! Thank you very much for the pull request. Please give me a day to do a quick review.

**Comment by The-Don-Himself** [comment]
ping @gurisko in case you had some time over the weekend.

**Comment by gurisko** [comment]
Thank you @eddy-lau very much for the PR and @The-Don-Himself for the ping. I didn't have much time testing it on both platforms but the code seemed to be good. Let's see what is the community feedback with the version 1.4.0.

**Comment by The-Don-Himself** [comment]
Thanks too @eddy-lau and @gurisko for merging. I'll try test it soon and report back any issues/features. Will you be tagging a new release?

**Comment by gurisko** [comment]
The release is out. Feel free to test it out directly - 1.4.0

**Comment by eddy-lau** [comment]
Thanks for merging my pull request. (@mfkenson).

**Pull request merged**
